import type { PaperlessDocument } from "@/lib/types";

export const documents: PaperlessDocument[] = [
  {
    id: 1842,
    title: "Invoice · Studio lighting",
    correspondent: "Nordlicht GmbH",
    documentType: "Invoice",
    tags: ["Business", "Equipment"],
    created: "Jun 24, 2026",
    added: "Today, 09:42",
    pages: 2,
    size: "284 KB",
    status: "review",
    accent: "blue",
  },
  {
    id: 1841,
    title: "Electricity statement · June",
    correspondent: "Lumen Energy",
    documentType: "Statement",
    tags: ["Home", "Utilities"],
    created: "Jun 23, 2026",
    added: "Today, 08:17",
    pages: 3,
    size: "1.2 MB",
    status: "review",
    accent: "ochre",
  },
  {
    id: 1839,
    title: "Train tickets · Copenhagen",
    correspondent: "Deutsche Bahn",
    documentType: "Receipt",
    tags: ["Travel", "Reimbursable"],
    created: "Jun 22, 2026",
    added: "Yesterday",
    pages: 1,
    size: "198 KB",
    status: "review",
    accent: "sage",
  },
  {
    id: 1836,
    title: "Health insurance policy update",
    correspondent: "TK",
    documentType: "Letter",
    tags: ["Personal", "Insurance"],
    created: "Jun 19, 2026",
    added: "Jun 20",
    pages: 5,
    size: "2.4 MB",
    status: "ready",
    accent: "plum",
  },
  {
    id: 1831,
    title: "Q2 software subscriptions",
    correspondent: "Various",
    documentType: "Report",
    tags: ["Business", "Finance"],
    created: "Jun 16, 2026",
    added: "Jun 17",
    pages: 4,
    size: "782 KB",
    status: "ready",
    accent: "slate",
  },
  {
    id: 1827,
    title: "Rental agreement · Kreuzberg",
    correspondent: "Hausverwaltung Mitte",
    documentType: "Contract",
    tags: ["Home", "Archive"],
    created: "Jun 10, 2026",
    added: "Jun 12",
    pages: 12,
    size: "4.8 MB",
    status: "ready",
    accent: "ochre",
  },
];

export const correspondents = [
  "Nordlicht GmbH",
  "Lumen Energy",
  "Deutsche Bahn",
  "TK",
  "Various",
  "Hausverwaltung Mitte",
];

export const documentTypes = [
  "Invoice",
  "Statement",
  "Receipt",
  "Letter",
  "Report",
  "Contract",
];

export const availableTags = [
  "Business",
  "Equipment",
  "Home",
  "Utilities",
  "Travel",
  "Reimbursable",
  "Personal",
  "Insurance",
  "Finance",
  "Archive",
];
